import urllib2
import json
import helperFunctions
import akronSBDC
import akronSCORE
import codeAkronFacebook
import ecdi
import greaterAkronCoC
import glide
import goodwill
import jumpstart
import launchNET
import ksuCCPD
import glyphixStudio
import magnet
import ODSA

#print akronSBDC.getJSON()
#print akronSCORE.getJSON()
#print ecdi.getJSONAkron()
#print ecdi.getJSONColumbus()
#print ecdi.getJSONCleveland()
#print ecdi.getJSONToledo()
#print goodwill.getJSON()
#greaterAkronCoC.getJSON() #still needs done
#print glide.getJSON()
#print jumpstart.getJSON()
#print launchNET.getJSON()
#print ksuCCPD.getJSON()
#print glyphixStudio.getJSON()
#print magnet.getJSON()
#print DSA.getJSON()